version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
