run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - dupl # allow duplication
    - funlen # allow long functions
    - testpackage # unwanted convention    
    - gomnd # allow some magic numbers
    - wsl # unwanted amount of whitespace
    - godox # allow TODOs
    - interfacer # deprecated by the author for having too many false positives
    - gocognit # allow higher cognitive complexity
    - nestif # allow deep nesting
    - paralleltest # code is not thread safe so skip parallel testing demands.
    - unparam # allow constant parameters
    - goerr113 # allow "dynamic" errors
    - nlreturn # don't enforce whitespace before return
    - wrapcheck # don't enforce error wrapping
    - exhaustivestruct # don't require exhaustive structs
    - durationcheck # has false positives
    - maligned # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - exhaustive # unwanted

linters-settings:
  cyclop:
    max-complexity: 20
