// Code generated by "stringer -type EventType -trimprefix EventType"; DO NOT EDIT.

package qualisys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeConnected-1]
	_ = x[EventTypeConnectionClosed-2]
	_ = x[EventTypeCaptureStarted-3]
	_ = x[EventTypeCaptureStopped-4]
	_ = x[EventTypeCaptureFetchingFinished-5]
	_ = x[EventTypeCalibrationStarted-6]
	_ = x[EventTypeCalibrationStopped-7]
	_ = x[EventTypeRtFromFileStarted-8]
	_ = x[EventTypeRtFromFileStopped-9]
	_ = x[EventTypeWaitingForTrigger-10]
	_ = x[EventTypeCameraSettingsChanged-11]
	_ = x[EventTypeQTMShuttingDown-12]
	_ = x[EventTypeCaptureSaved-13]
	_ = x[EventTypeReprocessingStarted-14]
	_ = x[EventTypeReprocessingStopped-15]
	_ = x[EventTypeTrigger-16]
	_ = x[EventTypeNone-17]
}

const _EventType_name = "ConnectedConnectionClosedCaptureStartedCaptureStoppedCaptureFetchingFinishedCalibrationStartedCalibrationStoppedRtFromFileStartedRtFromFileStoppedWaitingForTriggerCameraSettingsChangedQTMShuttingDownCaptureSavedReprocessingStartedReprocessingStoppedTriggerNone"

var _EventType_index = [...]uint16{0, 9, 25, 39, 53, 76, 94, 112, 129, 146, 163, 184, 199, 211, 230, 249, 256, 260}

func (i EventType) String() string {
	i -= 1
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
