// Code generated by "stringer -type LedColor -trimprefix LedColor"; DO NOT EDIT.

package qualisys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LedColorAmber-0]
	_ = x[LedColorGreen-1]
	_ = x[LedColorAll-2]
}

const _LedColor_name = "AmberGreenAll"

var _LedColor_index = [...]uint8{0, 5, 10, 13}

func (i LedColor) String() string {
	if i >= LedColor(len(_LedColor_index)-1) {
		return "LedColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LedColor_name[_LedColor_index[i]:_LedColor_index[i+1]]
}
