// Code generated by "stringer -type LedMode -trimprefix LedMode"; DO NOT EDIT.

package qualisys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LedModeOn-0]
	_ = x[LedModeOff-1]
	_ = x[LedModePulsing-2]
}

const _LedMode_name = "OnOffPulsing"

var _LedMode_index = [...]uint8{0, 2, 5, 12}

func (i LedMode) String() string {
	if i >= LedMode(len(_LedMode_index)-1) {
		return "LedMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LedMode_name[_LedMode_index[i]:_LedMode_index[i+1]]
}
