// Code generated by "stringer -type PacketType -trimprefix PacketType"; DO NOT EDIT.

package qualisys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketTypeError-0]
	_ = x[PacketTypeCommand-1]
	_ = x[PacketTypeXML-2]
	_ = x[PacketTypeData-3]
	_ = x[PacketTypeNoMoreData-4]
	_ = x[PacketTypeC3DFile-5]
	_ = x[PacketTypeEvent-6]
	_ = x[PacketTypeDiscover-7]
	_ = x[PacketTypeQTMFile-8]
	_ = x[PacketTypeNone-9]
}

const _PacketType_name = "ErrorCommandXMLDataNoMoreDataC3DFileEventDiscoverQTMFileNone"

var _PacketType_index = [...]uint8{0, 5, 12, 15, 19, 29, 36, 41, 49, 56, 60}

func (i PacketType) String() string {
	if i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
