// Code generated by "stringer -type ParameterType -trimprefix ParameterType"; DO NOT EDIT.

package qualisys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParameterTypeAll-0]
	_ = x[ParameterTypeGeneral-1]
	_ = x[ParameterTypeCalibration-2]
	_ = x[ParameterType3D-3]
	_ = x[ParameterType6D-4]
	_ = x[ParameterTypeAnalog-5]
	_ = x[ParameterTypeForce-6]
	_ = x[ParameterTypeImage-7]
	_ = x[ParameterTypeGazeVector-8]
	_ = x[ParameterTypeEyeTracker-9]
	_ = x[ParameterTypeSkeleton-10]
}

const _ParameterType_name = "AllGeneralCalibration3D6DAnalogForceImageGazeVectorEyeTrackerSkeleton"

var _ParameterType_index = [...]uint8{0, 3, 10, 21, 23, 25, 31, 36, 41, 51, 61, 69}

func (i ParameterType) String() string {
	if i < 0 || i >= ParameterType(len(_ParameterType_index)-1) {
		return "ParameterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParameterType_name[_ParameterType_index[i]:_ParameterType_index[i+1]]
}
