// Code generated by "stringer -type StreamRateType -trimprefix StreamRateType"; DO NOT EDIT.

package qualisys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StreamRateTypeAllFrames-0]
	_ = x[StreamRateTypeFrequency-1]
	_ = x[StreamRateTypeFrequencyDivisor-2]
}

const _StreamRateType_name = "AllFramesFrequencyFrequencyDivisor"

var _StreamRateType_index = [...]uint8{0, 9, 18, 34}

func (i StreamRateType) String() string {
	if i < 0 || i >= StreamRateType(len(_StreamRateType_index)-1) {
		return "StreamRateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StreamRateType_name[_StreamRateType_index[i]:_StreamRateType_index[i+1]]
}
