name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ^1.17

      - name: Make
        run: make
