// Code generated by "stringer -type TimecodeType -trimprefix TimecodeType"; DO NOT EDIT.

package packets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimecodeTypeSMPTE-0]
	_ = x[TimecodeTypeIRIG-1]
	_ = x[TimecodeTypeCameraTime-2]
}

const _TimecodeType_name = "SMPTEIRIGCameraTime"

var _TimecodeType_index = [...]uint8{0, 5, 9, 19}

func (i TimecodeType) String() string {
	if i >= TimecodeType(len(_TimecodeType_index)-1) {
		return "TimecodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimecodeType_name[_TimecodeType_index[i]:_TimecodeType_index[i+1]]
}
